### ISSUE TITLE
logo and list of games overlap

### ISSUE THREAD

**Issue by mistepien** [c64-dev/es-theme-c64-Origins#1]
On 1080p  game logo overlaps with 2 first position of game list.

**Comment by c64-dev** [comment]
Hi, I have tested the theme in my system in 1080 with 50 different systems and they all work fine. 
Can you give me some more information? 
1. Which game logo do you refer to? Do you mean the system logo (Amiga, Nintendo NES, etc)? 
2. When you say it overlaps the first 2 positions of the game list what do you mean?
On the gamelist there is nothing other than the list itself.

**Comment by c64-dev** [comment]
No response. Closing
